from class_collection import Car
car1=Car("Mustang",1996,"Black",False)
car2=Car("Camry",2005,"White",True)
car3=Car("Civic",2010,"Red",True)
print(car1)
print(car1.model)
print(car2.year)
print(car3.colour)
car1.drive()
car2.drive()
car1.stop()
car2.stop()
car1.describe()
car2.describe()
car3.describe()